name: gitdata
channels:
  - conda-forge
dependencies:
  # Core stack
  - python=3.10
  - build
  - bump2version
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - pip
  - twine
  # Utilities
  - pyprojroot
  - python-dotenv
  - s3fs-fuse
  # CLI development
  - typer
  - typer-cli
  # Software testing
  - hypothesis
  - pytest
  - pytest-cov
  - coverage
  # Code Style Tools
  - black
  - darglint
  - flake8
  - interrogate
  - pre-commit
  - pylint
  # Documentation
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  # pip dependencies
  - pip:
      # Place packages that cannot be installed by conda in this section.
      - mknotebooks
